[CmdletBinding()]
param(
  [switch]$SkipBuild
)

$ErrorActionPreference = "Stop"

$repositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$extensionName = "cocos-playable-packer"
$extensionRoot = Join-Path $repositoryRoot "extensions\$extensionName"
$packageFile = Join-Path $extensionRoot "package.json"

if (-not (Test-Path -LiteralPath $packageFile)) {
  throw "Creator extension package.json was not found: $packageFile"
}

if (-not $SkipBuild) {
  # Both directories are generated by TypeScript. Clearing them prevents stale
  # compiled files from being staged into the release runtime.
  $generatedDirectories = @(
    (Join-Path $repositoryRoot "dist"),
    (Join-Path $extensionRoot "dist")
  )
  foreach ($directory in $generatedDirectories) {
    if (Test-Path -LiteralPath $directory) {
      Remove-Item -LiteralPath $directory -Recurse -Force
    }
  }

  Write-Host "Rebuilding the Creator extension from clean dist directories..."
  Push-Location $repositoryRoot
  try {
    & npm run creator:build
    if ($LASTEXITCODE -ne 0) { throw "Creator extension build failed." }
  } finally {
    Pop-Location
  }
}

$requiredPaths = @(
  "dist\main.js",
  "dist\panels\default\index.js",
  "runtime\dist\creator-worker\playable-build-worker.js",
  "runtime\node_modules"
)
foreach ($relativePath in $requiredPaths) {
  $path = Join-Path $extensionRoot $relativePath
  if (-not (Test-Path -LiteralPath $path)) {
    throw "Required release file is missing: $path. Run without -SkipBuild after installing dependencies."
  }
}

$packageContents = Get-Content -LiteralPath $packageFile -Raw
$versionMatch = [regex]::Match($packageContents, '(?m)^\s*"version"\s*:\s*"(?<version>[^"]+)"')
$version = $versionMatch.Groups["version"].Value
if ([string]::IsNullOrWhiteSpace($version)) { throw "Extension version is missing from $packageFile" }

$releaseRoot = Join-Path $repositoryRoot "release"
$archivePath = Join-Path $releaseRoot "$extensionName-v$version.zip"
$stagingRoot = Join-Path $releaseRoot ".package-staging-$extensionName"
$stagingExtensionRoot = Join-Path $stagingRoot $extensionName
$stagingDemoRoot = Join-Path $stagingRoot "CocosDemo"
$demoProjectRoot = Join-Path $repositoryRoot "CocosDemo"
$demoExtensionsRoot = Join-Path $demoProjectRoot "extensions"
$demoExtensionRoot = Join-Path $demoExtensionsRoot $extensionName
$demoInstallStagingRoot = Join-Path $releaseRoot ".demo-install-$extensionName"

New-Item -ItemType Directory -Force -Path $releaseRoot | Out-Null
Remove-Item -LiteralPath $stagingRoot -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath $archivePath -Force -ErrorAction SilentlyContinue

try {
  New-Item -ItemType Directory -Force -Path $stagingExtensionRoot | Out-Null

  # Only production files are copied. runtime/src is included because the image
  # quality flow invokes its TypeScript CLI through tsx at runtime.
  # Caches, workspaces, and logs stay out. The bundled default loading Logo is
  # intentionally included so the installed extension has a ready-made asset.
  foreach ($file in @(".gitignore", "package.json", "README.md")) {
    Copy-Item -LiteralPath (Join-Path $extensionRoot $file) -Destination $stagingExtensionRoot
  }
  foreach ($directory in @(".logo-cache", "dist", "runtime\src", "runtime\node_modules", "static\branding", "static\style", "static\template")) {
    $source = Join-Path $extensionRoot $directory
    $destination = Join-Path $stagingExtensionRoot $directory
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $destination) | Out-Null
    Copy-Item -LiteralPath $source -Destination $destination -Recurse -Force
  }
  $runtimeDist = Join-Path $extensionRoot "runtime\dist"
  Get-ChildItem -LiteralPath $runtimeDist -Recurse -File -Filter "*.js" | ForEach-Object {
    $relativePath = $_.FullName.Substring($runtimeDist.Length).TrimStart([char[]]@('\', '/'))
    $destination = Join-Path $stagingExtensionRoot "runtime\dist\$relativePath"
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $destination) | Out-Null
    Copy-Item -LiteralPath $_.FullName -Destination $destination -Force
  }
  foreach ($file in @("static\icon.svg", "static\cocos-playable-packer-tab-icon.svg", "static\cocos-playable-packer-app-icon.png", "runtime\package.json", "runtime\package-lock.json")) {
    $source = Join-Path $extensionRoot $file
    $destination = Join-Path $stagingExtensionRoot $file
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $destination) | Out-Null
    Copy-Item -LiteralPath $source -Destination $destination -Force
  }

  # Include the demo project as source material. Creator regenerates these
  # directories, so shipping them would make the release unnecessarily large
  # and can make the project depend on the machine that produced the archive.
  # The installed extension is intentionally omitted as well: the extension
  # above is the single release copy and is installed into the working demo
  # below for verification.
  $demoExcludedDirectories = @(".git", "temp", "library", "build", "extensions")
  New-Item -ItemType Directory -Force -Path $stagingDemoRoot | Out-Null
  Get-ChildItem -LiteralPath $demoProjectRoot -Recurse -Force -File | ForEach-Object {
    $relativePath = $_.FullName.Substring($demoProjectRoot.Length).TrimStart([char[]]@('\', '/'))
    $normalizedRelativePath = $relativePath -replace '\\', '/'
    $isExcluded = $false
    foreach ($excludedDirectory in $demoExcludedDirectories) {
      if ($normalizedRelativePath -eq $excludedDirectory -or $normalizedRelativePath.StartsWith("$excludedDirectory/", [StringComparison]::OrdinalIgnoreCase)) {
        $isExcluded = $true
        break
      }
    }
    if ($isExcluded) { return }

    $destination = Join-Path $stagingDemoRoot $relativePath
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $destination) | Out-Null
    Copy-Item -LiteralPath $_.FullName -Destination $destination -Force
  }

  Add-Type -AssemblyName System.IO.Compression.FileSystem
  [System.IO.Compression.ZipFile]::CreateFromDirectory(
    $stagingRoot,
    $archivePath,
    [System.IO.Compression.CompressionLevel]::Optimal,
    $false
  )

  $archiveEntries = [System.IO.Compression.ZipFile]::OpenRead($archivePath).Entries.FullName |
    ForEach-Object { $_ -replace '\\', '/' }
  $forbiddenPattern = '(^|/)(\.squoosh-cache|\.tinypng-cache|\.packer-web|workspaces|web-mobile|node_modules/\.cache|CocosDemo/(temp|library|build|extensions))(/|$)|/runtime/dist/.*\.(html|json|zip)$'
  $forbidden = @($archiveEntries | Where-Object { $_ -match $forbiddenPattern })
  if ($forbidden.Count -gt 0) {
    throw "Release archive contains excluded files: $($forbidden -join ', ')"
  }
  foreach ($relativePath in @("$extensionName/package.json", "$extensionName/dist/main.js", "$extensionName/runtime/dist/creator-worker/playable-build-worker.js")) {
    if ($archiveEntries -notcontains $relativePath) { throw "Release archive is missing: $relativePath" }
  }
  foreach ($relativePath in @("CocosDemo/package.json", "CocosDemo/tsconfig.json", "CocosDemo/assets/scene/main.scene")) {
    if ($archiveEntries -notcontains $relativePath) { throw "Release archive is missing demo file: $relativePath" }
  }

  # Install the exact release archive into CocosDemo. This deliberately avoids
  # copying from the working extension directory, so demo verification always
  # exercises the same files that will be distributed to users.
  if (-not (Test-Path -LiteralPath $demoProjectRoot)) {
    throw "CocosDemo project was not found: $demoProjectRoot"
  }
  Remove-Item -LiteralPath $demoInstallStagingRoot -Recurse -Force -ErrorAction SilentlyContinue
  Expand-Archive -LiteralPath $archivePath -DestinationPath $demoInstallStagingRoot -Force
  $installedPackageFile = Join-Path $demoInstallStagingRoot "$extensionName\package.json"
  if (-not (Test-Path -LiteralPath $installedPackageFile)) {
    throw "Release archive could not be installed into CocosDemo: missing $extensionName/package.json"
  }
  New-Item -ItemType Directory -Force -Path $demoExtensionsRoot | Out-Null
  Remove-Item -LiteralPath $demoExtensionRoot -Recurse -Force -ErrorAction SilentlyContinue
  New-Item -ItemType Directory -Force -Path $demoExtensionRoot | Out-Null
  Get-ChildItem -LiteralPath (Join-Path $demoInstallStagingRoot $extensionName) -Force | ForEach-Object {
    Copy-Item -LiteralPath $_.FullName -Destination $demoExtensionRoot -Recurse -Force
  }
  $installedVersion = (Get-Content -LiteralPath (Join-Path $demoExtensionRoot "package.json") -Raw | ConvertFrom-Json).version
  if ($installedVersion -ne $version) {
    throw "CocosDemo extension version mismatch: expected $version, got $installedVersion"
  }

  $sizeMiB = [Math]::Round((Get-Item -LiteralPath $archivePath).Length / 1MB, 2)
  Write-Host "Release archive created: $archivePath ($sizeMiB MiB)"
  Write-Host "Release archive installed into CocosDemo: $demoExtensionRoot"
} finally {
  Remove-Item -LiteralPath $stagingRoot -Recurse -Force -ErrorAction SilentlyContinue
  Remove-Item -LiteralPath $demoInstallStagingRoot -Recurse -Force -ErrorAction SilentlyContinue
}
