[CmdletBinding()]
param(
  [switch]$SkipBuild
)

$ErrorActionPreference = "Stop"

$repositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$extensionName = "cocos-playable-packer"
$extensionRoot = Join-Path $repositoryRoot "extensions\$extensionName"
$packageFile = Join-Path $extensionRoot "package.json"

if (-not (Test-Path -LiteralPath $packageFile)) {
  throw "Creator extension package.json was not found: $packageFile"
}

if (-not $SkipBuild) {
  # Both directories are generated by TypeScript. Clearing them prevents stale
  # compiled files from being staged into the release runtime.
  $generatedDirectories = @(
    (Join-Path $repositoryRoot "dist"),
    (Join-Path $extensionRoot "dist")
  )
  foreach ($directory in $generatedDirectories) {
    if (Test-Path -LiteralPath $directory) {
      Remove-Item -LiteralPath $directory -Recurse -Force
    }
  }

  Write-Host "Rebuilding the Creator extension from clean dist directories..."
  Push-Location $repositoryRoot
  try {
    & npm run creator:build
    if ($LASTEXITCODE -ne 0) { throw "Creator extension build failed." }
  } finally {
    Pop-Location
  }
}

$requiredPaths = @(
  "dist\main.js",
  "dist\panels\default\index.js",
  "runtime\dist\creator-worker\playable-build-worker.js",
  "runtime\node_modules"
)
foreach ($relativePath in $requiredPaths) {
  $path = Join-Path $extensionRoot $relativePath
  if (-not (Test-Path -LiteralPath $path)) {
    throw "Required release file is missing: $path. Run without -SkipBuild after installing dependencies."
  }
}

$packageContents = Get-Content -LiteralPath $packageFile -Raw
$versionMatch = [regex]::Match($packageContents, '(?m)^\s*"version"\s*:\s*"(?<version>[^"]+)"')
$version = $versionMatch.Groups["version"].Value
if ([string]::IsNullOrWhiteSpace($version)) { throw "Extension version is missing from $packageFile" }

$releaseRoot = Join-Path $repositoryRoot "release"
$archivePath = Join-Path $releaseRoot "$extensionName-v$version.zip"
$stagingRoot = Join-Path $releaseRoot ".package-staging-$extensionName"
$stagingExtensionRoot = Join-Path $stagingRoot $extensionName

New-Item -ItemType Directory -Force -Path $releaseRoot | Out-Null
Remove-Item -LiteralPath $stagingRoot -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath $archivePath -Force -ErrorAction SilentlyContinue

try {
  New-Item -ItemType Directory -Force -Path $stagingExtensionRoot | Out-Null

  # Only production files are copied. runtime/src is included because the image
  # quality flow invokes its TypeScript CLI through tsx at runtime.
  # Caches, workspaces, logs, and locally saved loading-logo assets stay out.
  foreach ($file in @(".gitignore", "package.json", "README.md")) {
    Copy-Item -LiteralPath (Join-Path $extensionRoot $file) -Destination $stagingExtensionRoot
  }
  foreach ($directory in @("dist", "runtime\src", "runtime\node_modules", "static\branding", "static\style", "static\template")) {
    $source = Join-Path $extensionRoot $directory
    $destination = Join-Path $stagingExtensionRoot $directory
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $destination) | Out-Null
    Copy-Item -LiteralPath $source -Destination $destination -Recurse -Force
  }
  $runtimeDist = Join-Path $extensionRoot "runtime\dist"
  Get-ChildItem -LiteralPath $runtimeDist -Recurse -File -Filter "*.js" | ForEach-Object {
    $relativePath = $_.FullName.Substring($runtimeDist.Length).TrimStart([char[]]@('\', '/'))
    $destination = Join-Path $stagingExtensionRoot "runtime\dist\$relativePath"
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $destination) | Out-Null
    Copy-Item -LiteralPath $_.FullName -Destination $destination -Force
  }
  foreach ($file in @("static\icon.svg", "static\cocos-playable-packer-tab-icon.svg", "static\cocos-playable-packer-app-icon.png", "runtime\package.json", "runtime\package-lock.json")) {
    $source = Join-Path $extensionRoot $file
    $destination = Join-Path $stagingExtensionRoot $file
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $destination) | Out-Null
    Copy-Item -LiteralPath $source -Destination $destination -Force
  }

  Add-Type -AssemblyName System.IO.Compression.FileSystem
  [System.IO.Compression.ZipFile]::CreateFromDirectory(
    $stagingRoot,
    $archivePath,
    [System.IO.Compression.CompressionLevel]::Optimal,
    $false
  )

  $archiveEntries = [System.IO.Compression.ZipFile]::OpenRead($archivePath).Entries.FullName |
    ForEach-Object { $_ -replace '\\', '/' }
  $forbiddenPattern = '(^|/)(\.squoosh-cache|\.tinypng-cache|\.packer-web|workspaces|web-mobile|node_modules/\.cache)(/|$)|(^|/)loading-logo\.|/runtime/dist/.*\.(html|json|zip)$'
  $forbidden = @($archiveEntries | Where-Object { $_ -match $forbiddenPattern })
  if ($forbidden.Count -gt 0) {
    throw "Release archive contains excluded files: $($forbidden -join ', ')"
  }
  foreach ($relativePath in @("$extensionName/package.json", "$extensionName/dist/main.js", "$extensionName/runtime/dist/creator-worker/playable-build-worker.js")) {
    if ($archiveEntries -notcontains $relativePath) { throw "Release archive is missing: $relativePath" }
  }

  $sizeMiB = [Math]::Round((Get-Item -LiteralPath $archivePath).Length / 1MB, 2)
  Write-Host "Release archive created: $archivePath ($sizeMiB MiB)"
} finally {
  Remove-Item -LiteralPath $stagingRoot -Recurse -Force -ErrorAction SilentlyContinue
}
