import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { createGroupedChannelWebMvpIndexHtml } from "./web-config-grouped-channel-ui.js";
import type { WebVersionInfo } from "./web-version-info.js";

const ZIP_UTF8_FLAG = 0x0800;

function replaceOnce(source: string, search: string, replacement: string): string {
  const index = source.indexOf(search);
  if (index < 0) {
    throw new Error(`Playable SDK 下载 UI 缺少插入点：${search.slice(0, 100)}`);
  }
  return `${source.slice(0, index)}${replacement}${source.slice(index + search.length)}`;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function normalizeVersion(value: string): string {
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : "dev";
}

function versionedArchiveBaseName(version: string): string {
  const safeVersion = normalizeVersion(version)
    .replace(/[^0-9A-Za-z._-]+/g, "-")
    .replace(/^-+|-+$/g, "") || "dev";
  return `CocosPlayableSDK-v${safeVersion}`;
}

function readSdkSource(fileName: string): string {
  const moduleDirectory = path.dirname(fileURLToPath(import.meta.url));
  const candidates = [
    path.resolve(moduleDirectory, "../sdk", fileName),
    path.resolve(process.cwd(), "src/sdk", fileName),
  ];

  for (const candidate of candidates) {
    try {
      return readFileSync(candidate, "utf8");
    } catch {
      // 尝试下一个源码位置。
    }
  }

  throw new Error(`无法读取 Playable SDK 下载源文件：${fileName}`);
}

function createVersionHeader(version: string): string {
  return `/**\n * Cocos Playable SDK v${version}\n * Generated by Cocos Playable Packer v${version}.\n */\n`;
}

function createDownloadSources(appVersion: string): Record<string, string> {
  const version = normalizeVersion(appVersion);
  const importPattern = /\.\/playable-sdk-types\.js/g;
  const versionPattern = /export const PLAYABLE_SDK_VERSION = "[^"]*";/;
  const header = createVersionHeader(version);

  const sdkSource = readSdkSource("playable-sdk.ts")
    .replace(importPattern, "./PlayableSDKTypes");
  const typesSource = readSdkSource("playable-sdk-types.ts")
    .replace(
      versionPattern,
      `export const PLAYABLE_SDK_VERSION = ${JSON.stringify(version)};`,
    );
  const globalSource = readSdkSource("playable-runtime-global.d.ts")
    .replace(importPattern, "./PlayableSDKTypes");

  return {
    "PlayableSDK.ts": header + sdkSource,
    "PlayableSDKTypes.ts": header + typesSource,
    "PlayableSDKGlobal.d.ts": header + globalSource,
  };
}

function calculateCrc32(bytes: Uint8Array): number {
  let crc = 0xffffffff;
  for (const byte of bytes) {
    crc ^= byte;
    for (let bit = 0; bit < 8; bit += 1) {
      crc = (crc >>> 1) ^ (0xedb88320 & -(crc & 1));
    }
  }
  return (crc ^ 0xffffffff) >>> 0;
}

function createStoredZip(entries: Record<string, string>, directoryName: string): Buffer {
  const localParts: Buffer[] = [];
  const centralParts: Buffer[] = [];
  let localOffset = 0;

  for (const [fileName, source] of Object.entries(entries)) {
    const archivePath = `${directoryName}/${fileName}`;
    const nameBytes = Buffer.from(archivePath, "utf8");
    const contentBytes = Buffer.from(source, "utf8");
    const crc32 = calculateCrc32(contentBytes);

    const localHeader = Buffer.alloc(30);
    localHeader.writeUInt32LE(0x04034b50, 0);
    localHeader.writeUInt16LE(20, 4);
    localHeader.writeUInt16LE(ZIP_UTF8_FLAG, 6);
    localHeader.writeUInt16LE(0, 8);
    localHeader.writeUInt16LE(0, 10);
    localHeader.writeUInt16LE(0, 12);
    localHeader.writeUInt32LE(crc32, 14);
    localHeader.writeUInt32LE(contentBytes.byteLength, 18);
    localHeader.writeUInt32LE(contentBytes.byteLength, 22);
    localHeader.writeUInt16LE(nameBytes.byteLength, 26);
    localHeader.writeUInt16LE(0, 28);

    const localPart = Buffer.concat([localHeader, nameBytes, contentBytes]);
    localParts.push(localPart);

    const centralHeader = Buffer.alloc(46);
    centralHeader.writeUInt32LE(0x02014b50, 0);
    centralHeader.writeUInt16LE(20, 4);
    centralHeader.writeUInt16LE(20, 6);
    centralHeader.writeUInt16LE(ZIP_UTF8_FLAG, 8);
    centralHeader.writeUInt16LE(0, 10);
    centralHeader.writeUInt16LE(0, 12);
    centralHeader.writeUInt16LE(0, 14);
    centralHeader.writeUInt32LE(crc32, 16);
    centralHeader.writeUInt32LE(contentBytes.byteLength, 20);
    centralHeader.writeUInt32LE(contentBytes.byteLength, 24);
    centralHeader.writeUInt16LE(nameBytes.byteLength, 28);
    centralHeader.writeUInt16LE(0, 30);
    centralHeader.writeUInt16LE(0, 32);
    centralHeader.writeUInt16LE(0, 34);
    centralHeader.writeUInt16LE(0, 36);
    centralHeader.writeUInt32LE(0, 38);
    centralHeader.writeUInt32LE(localOffset, 42);
    centralParts.push(Buffer.concat([centralHeader, nameBytes]));

    localOffset += localPart.byteLength;
  }

  const centralDirectory = Buffer.concat(centralParts);
  const endRecord = Buffer.alloc(22);
  endRecord.writeUInt32LE(0x06054b50, 0);
  endRecord.writeUInt16LE(0, 4);
  endRecord.writeUInt16LE(0, 6);
  endRecord.writeUInt16LE(centralParts.length, 8);
  endRecord.writeUInt16LE(centralParts.length, 10);
  endRecord.writeUInt32LE(centralDirectory.byteLength, 12);
  endRecord.writeUInt32LE(localOffset, 16);
  endRecord.writeUInt16LE(0, 20);

  return Buffer.concat([...localParts, centralDirectory, endRecord]);
}

export function createPlayableSdkDownloadZip(appVersion: string): Buffer {
  const archiveBaseName = versionedArchiveBaseName(appVersion);
  return createStoredZip(createDownloadSources(appVersion), archiveBaseName);
}

function safeScriptJson(value: unknown): string {
  return JSON.stringify(value)
    .replace(/</g, "\\u003c")
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

export function createPlayableSdkDownloadWebMvpIndexHtml(
  versionInfo: WebVersionInfo,
): string {
  let html = createGroupedChannelWebMvpIndexHtml(versionInfo);
  const appVersion = normalizeVersion(versionInfo.appVersion);
  const archiveBaseName = versionedArchiveBaseName(appVersion);
  const zipFileName = `${archiveBaseName}.zip`;
  const zipBase64 = safeScriptJson(
    createPlayableSdkDownloadZip(appVersion).toString("base64"),
  );
  const escapedVersion = escapeHtml(appVersion);
  const escapedArchiveBaseName = escapeHtml(archiveBaseName);

  html = replaceOnce(
    html,
    "    .error { color: #fca5a5; }",
    `    .playable-sdk-download-actions { display: flex; gap: 8px; flex-wrap: wrap; }
    .playable-sdk-download-actions button { width: auto; }
    .playable-sdk-download-note { color: #9ca3af; line-height: 1.55; }
    .error { color: #fca5a5; }`,
  );

  html = replaceOnce(
    html,
    '      <div id="channelSummary" class="summary"></div>',
    `      <div id="playableSdkDownloadField" class="field">
        <label>游戏侧 Playable SDK v${escapedVersion}</label>
        <div class="playable-sdk-download-actions">
          <button id="downloadPlayableSdkZipButton" class="secondary" type="button">下载 ${escapedArchiveBaseName}.zip</button>
        </div>
        <small class="playable-sdk-download-note">ZIP 内的 ${escapedArchiveBaseName} 文件夹包含 PlayableSDK.ts、PlayableSDKTypes.ts 和 PlayableSDKGlobal.d.ts。三个文件头和 SDK 版本常量均与当前网站版本 v${escapedVersion} 一致。</small>
      </div>
      <div id="channelSummary" class="summary"></div>`,
  );

  html = replaceOnce(
    html,
    "    const configSummary = document.getElementById('configSummary');",
    `    const playableSdkZipBase64 = ${zipBase64};
    const downloadPlayableSdkZipButton = document.getElementById('downloadPlayableSdkZipButton');
    const configSummary = document.getElementById('configSummary');`,
  );

  html = replaceOnce(
    html,
    "    function readConfig() {",
    `    function decodeBase64Bytes(base64) {
      const binary = atob(base64);
      const bytes = new Uint8Array(binary.length);
      for (let index = 0; index < binary.length; index += 1) {
        bytes[index] = binary.charCodeAt(index);
      }
      return bytes;
    }

    function downloadPlayableSdkZip() {
      const bytes = decodeBase64Bytes(playableSdkZipBase64);
      const blob = new Blob([bytes], { type: 'application/zip' });
      const url = URL.createObjectURL(blob);
      const anchor = document.createElement('a');
      anchor.href = url;
      anchor.download = ${safeScriptJson(zipFileName)};
      document.body.appendChild(anchor);
      anchor.click();
      anchor.remove();
      setTimeout(() => URL.revokeObjectURL(url), 0);
    }

    function readConfig() {`,
  );

  html = replaceOnce(
    html,
    "    payloadEncodingInput.addEventListener('change', refreshConfigUi);",
    `    downloadPlayableSdkZipButton.addEventListener('click', downloadPlayableSdkZip);
    payloadEncodingInput.addEventListener('change', refreshConfigUi);`,
  );

  html = replaceOnce(
    html,
    "        createConfigGroup('目标渠道', 'channel', [document.getElementById('channelPlatformGroup')?.closest('.field') || null]),",
    "        createConfigGroup('目标渠道', 'channel', [document.getElementById('channelPlatformGroup')?.closest('.field') || null, document.getElementById('playableSdkDownloadField')]),",
  );

  return html;
}
